class LanguageConfig {
  static Map<String, Map<String, String>> translations = {
    'en': {
      'selectDevice': 'Select Device',
      'noDevices': 'No devices available',
      'selectDeviceToMonitor': 'Please select a device to monitor',
      'continue': 'Continue',
      'retry': 'Retry',
      'errorLoading': 'Error loading data',
      'overview': 'Overview',
      'records': 'Records',
      'settings': 'Settings',
      'appearance': 'Appearance',
      'darkMode': 'Dark Mode',
      'language': 'Language',
      'english': 'English',
      'chinese': 'Chinese',
      'noData': 'No data available',
      'noDataForDate': 'No data available for selected date',
      'recentActivity': 'Recent Activity Records',
      'device': 'Device',
      'activity': 'Activity',
      'time': 'Time',
      'duration': 'Duration',
      'feeding': 'Feeding',
      'playing': 'Playing',
      'running': 'Running',
      'sniffing': 'Sniffing',
      'stilling': 'Stilling',
      'walking': 'Walking',
    },
    'zh': {
      'selectDevice': '选择设备',
      'noDevices': '暂无可用设备',
      'selectDeviceToMonitor': '请选择要监控的设备',
      'continue': '继续',
      'retry': '重试',
      'errorLoading': '加载数据出错',
      'overview': '概览',
      'records': '记录',
      'settings': '设置',
      'appearance': '外观',
      'darkMode': '深色模式',
      'language': '语言',
      'english': '英语',
      'chinese': '中文',
      'noData': '暂无数据',
      'noDataForDate': '所选日期无数据',
      'recentActivity': '最近活动记录',
      'device': '设备',
      'activity': '活动',
      'time': '时间',
      'duration': '持续时间',
      'feeding': '进食',
      'playing': '玩耍',
      'running': '奔跑',
      'sniffing': '嗅探',
      'walking': '行走',
      'stilling': '静止',
    },
  };

  static String getTranslation(String key, String language) {
    return translations[language]?[key] ?? key;
  }
} 